/**
 * Seed reference data. Venue and business names are fictional; any resemblance to
 * a real Brussels studio is coincidental and must stay that way — this data ships
 * to staging where screenshots get taken.
 */

export const BRUSSELS_DISTRICTS: { slug: string; name: string; lat: number; lon: number }[] = [
  { slug: 'bruxelles', name: 'Bruxelles', lat: 50.8467, lon: 4.3525 },
  { slug: 'ixelles', name: 'Ixelles', lat: 50.8235, lon: 4.3699 },
  { slug: 'etterbeek', name: 'Etterbeek', lat: 50.8365, lon: 4.3894 },
  { slug: 'saint-gilles', name: 'Saint-Gilles', lat: 50.8264, lon: 4.3452 },
  { slug: 'uccle', name: 'Uccle', lat: 50.8005, lon: 4.3376 },
  { slug: 'schaerbeek', name: 'Schaerbeek', lat: 50.8676, lon: 4.3737 },
  { slug: 'woluwe-saint-lambert', name: 'Woluwe-Saint-Lambert', lat: 50.8465, lon: 4.4262 },
  { slug: 'woluwe-saint-pierre', name: 'Woluwe-Saint-Pierre', lat: 50.8323, lon: 4.4384 },
  { slug: 'auderghem', name: 'Auderghem', lat: 50.8158, lon: 4.4272 },
  { slug: 'forest', name: 'Forest', lat: 50.8106, lon: 4.3232 },
  { slug: 'anderlecht', name: 'Anderlecht', lat: 50.8367, lon: 4.3096 },
  { slug: 'molenbeek', name: 'Molenbeek-Saint-Jean', lat: 50.8551, lon: 4.3242 },
  { slug: 'saint-josse', name: 'Saint-Josse-ten-Noode', lat: 50.8535, lon: 4.3706 },
  { slug: 'koekelberg', name: 'Koekelberg', lat: 50.8622, lon: 4.3283 },
  { slug: 'jette', name: 'Jette', lat: 50.8781, lon: 4.3263 },
  { slug: 'evere', name: 'Evere', lat: 50.8709, lon: 4.4021 },
  { slug: 'watermael-boitsfort', name: 'Watermael-Boitsfort', lat: 50.7988, lon: 4.4118 },
  { slug: 'berchem-sainte-agathe', name: 'Berchem-Sainte-Agathe', lat: 50.8646, lon: 4.2939 },
  { slug: 'ganshoren', name: 'Ganshoren', lat: 50.8714, lon: 4.3178 },
];

export const CATEGORIES: { slug: string; name: string; icon: string }[] = [
  { slug: 'fitness', name: 'Fitness', icon: 'dumbbell' },
  { slug: 'ems', name: 'EMS', icon: 'zap' },
  { slug: 'pilates', name: 'Pilates', icon: 'flower' },
  { slug: 'yoga', name: 'Yoga', icon: 'lotus' },
  { slug: 'boxing', name: 'Boxing', icon: 'boxing-glove' },
  { slug: 'crossfit', name: 'CrossFit', icon: 'kettlebell' },
  { slug: 'cycling', name: 'Cycling', icon: 'bike' },
  { slug: 'padel', name: 'Padel', icon: 'racket' },
  { slug: 'tennis', name: 'Tennis', icon: 'tennis-ball' },
  { slug: 'escalade', name: 'Escalade', icon: 'mountain' },
  { slug: 'danse', name: 'Danse', icon: 'music' },
  { slug: 'natation', name: 'Natation', icon: 'waves' },
  { slug: 'arts-martiaux', name: 'Arts martiaux', icon: 'sword' },
  { slug: 'personal-training', name: 'Personal Training', icon: 'user-check' },
  { slug: 'recovery', name: 'Recovery', icon: 'heart-pulse' },
  { slug: 'running', name: 'Running', icon: 'footprints' },
];

export interface SeedVenue {
  slug: string;
  name: string;
  businessSlug: string;
  district: string;
  lat: number;
  lon: number;
  address: string;
  postalCode: string;
  categories: string[];
  amenities: string[];
  description: string;
}

export const BUSINESSES: { slug: string; name: string; email: string }[] = [
  { slug: 'move-collective', name: 'Move Collective', email: 'contact@movecollective.test' },
  { slug: 'atelier-pulse', name: 'Atelier Pulse', email: 'hello@atelierpulse.test' },
  { slug: 'nordic-fit', name: 'Nordic Fit', email: 'info@nordicfit.test' },
  { slug: 'club-cinquantenaire', name: 'Club Cinquantenaire', email: 'contact@clubcinq.test' },
  { slug: 'racket-house', name: 'Racket House', email: 'play@rackethouse.test' },
  { slug: 'vertical-lab', name: 'Vertical Lab', email: 'climb@verticallab.test' },
  { slug: 'studio-lumen', name: 'Studio Lumen', email: 'hello@studiolumen.test' },
  { slug: 'forge-athletics', name: 'Forge Athletics', email: 'team@forgeathletics.test' },
];

export const VENUES: SeedVenue[] = [
  {
    slug: 'studio-move-ixelles',
    name: 'Studio Move Ixelles',
    businessSlug: 'move-collective',
    district: 'ixelles',
    lat: 50.8271,
    lon: 4.3718,
    address: 'Rue de la Brasserie 42',
    postalCode: '1050',
    categories: ['pilates', 'yoga'],
    amenities: ['Douches', 'Vestiaires', 'Tapis fournis', 'Casiers'],
    description:
      'Un studio lumineux à deux pas de Flagey, spécialisé en Pilates Reformer et Vinyasa. Petits groupes, coaching individualisé.',
  },
  {
    slug: 'studio-move-uccle',
    name: 'Studio Move Uccle',
    businessSlug: 'move-collective',
    district: 'uccle',
    lat: 50.8032,
    lon: 4.3391,
    address: 'Chaussée de Waterloo 890',
    postalCode: '1180',
    categories: ['pilates', 'recovery'],
    amenities: ['Douches', 'Vestiaires', 'Parking', 'Sauna'],
    description:
      'Le second studio du collectif, pensé pour la récupération : Reformer, mobilité et sauna infrarouge.',
  },
  {
    slug: 'atelier-pulse-saint-gilles',
    name: 'Atelier Pulse',
    businessSlug: 'atelier-pulse',
    district: 'saint-gilles',
    lat: 50.8281,
    lon: 4.3441,
    address: 'Rue de Moscou 18',
    postalCode: '1060',
    categories: ['ems', 'personal-training'],
    amenities: ['Douches', 'Serviettes', 'Tenue EMS fournie'],
    description:
      'Séances EMS de 20 minutes encadrées par un coach. Idéal pour tester une méthode intense sans y passer la soirée.',
  },
  {
    slug: 'nordic-fit-etterbeek',
    name: 'Nordic Fit Etterbeek',
    businessSlug: 'nordic-fit',
    district: 'etterbeek',
    lat: 50.8371,
    lon: 4.3902,
    address: 'Avenue des Casernes 31',
    postalCode: '1040',
    categories: ['fitness', 'crossfit'],
    amenities: ['Douches', 'Vestiaires', 'Parking vélo', 'Coach présent'],
    description:
      'Salle fonctionnelle avec plateau haltérophilie, cours collectifs et coaching. Ambiance club, pas usine.',
  },
  {
    slug: 'nordic-fit-schaerbeek',
    name: 'Nordic Fit Schaerbeek',
    businessSlug: 'nordic-fit',
    district: 'schaerbeek',
    lat: 50.8668,
    lon: 4.3729,
    address: 'Chaussée de Haecht 220',
    postalCode: '1030',
    categories: ['fitness', 'boxing'],
    amenities: ['Douches', 'Vestiaires', 'Sacs de frappe'],
    description:
      'Le club de quartier de Nordic Fit : renforcement, boxe loisir et circuits courts après le travail.',
  },
  {
    slug: 'club-cinquantenaire',
    name: 'Club Cinquantenaire',
    businessSlug: 'club-cinquantenaire',
    district: 'etterbeek',
    lat: 50.8402,
    lon: 4.3931,
    address: 'Avenue de la Renaissance 12',
    postalCode: '1000',
    categories: ['natation', 'fitness', 'recovery'],
    amenities: ['Piscine 25 m', 'Sauna', 'Hammam', 'Parking'],
    description:
      'Club complet avec piscine, espace bien-être et plateau cardio. Accès journée disponible.',
  },
  {
    slug: 'racket-house-woluwe',
    name: 'Racket House Woluwe',
    businessSlug: 'racket-house',
    district: 'woluwe-saint-lambert',
    lat: 50.8452,
    lon: 4.4281,
    address: 'Avenue Georges Henri 305',
    postalCode: '1200',
    categories: ['padel', 'tennis'],
    amenities: ['4 terrains padel', 'Location raquette', 'Bar', 'Parking'],
    description:
      'Quatre terrains de padel couverts et deux courts de tennis. Initiations encadrées chaque semaine.',
  },
  {
    slug: 'racket-house-auderghem',
    name: 'Racket House Auderghem',
    businessSlug: 'racket-house',
    district: 'auderghem',
    lat: 50.8171,
    lon: 4.4295,
    address: 'Boulevard du Souverain 240',
    postalCode: '1160',
    categories: ['padel'],
    amenities: ['6 terrains padel', 'Location raquette', 'Douches'],
    description: 'Le plus grand centre de padel du sud-est bruxellois, ouvert de 7 h à 23 h.',
  },
  {
    slug: 'vertical-lab-anderlecht',
    name: 'Vertical Lab',
    businessSlug: 'vertical-lab',
    district: 'anderlecht',
    lat: 50.8391,
    lon: 4.3112,
    address: 'Quai de Biestebroeck 300',
    postalCode: '1070',
    categories: ['escalade', 'fitness'],
    amenities: ['Bloc', 'Voies 15 m', 'Location chaussons', 'Café'],
    description:
      'Salle d’escalade de bloc et de difficulté dans une ancienne halle industrielle. Initiation débutant tous les samedis.',
  },
  {
    slug: 'studio-lumen-bruxelles',
    name: 'Studio Lumen',
    businessSlug: 'studio-lumen',
    district: 'bruxelles',
    lat: 50.8489,
    lon: 4.3568,
    address: 'Rue Antoine Dansaert 88',
    postalCode: '1000',
    categories: ['yoga', 'danse', 'recovery'],
    amenities: ['Tapis fournis', 'Vestiaires', 'Thé offert'],
    description:
      'Yoga doux, danse contemporaine et ateliers respiration au cœur du centre-ville.',
  },
  {
    slug: 'forge-athletics-forest',
    name: 'Forge Athletics',
    businessSlug: 'forge-athletics',
    district: 'forest',
    lat: 50.8128,
    lon: 4.3251,
    address: 'Avenue Van Volxem 210',
    postalCode: '1190',
    categories: ['crossfit', 'fitness'],
    amenities: ['Douches', 'Vestiaires', 'Coach', 'Parking'],
    description:
      'Box CrossFit affiliée avec programmation quotidienne et cours débutants trois fois par semaine.',
  },
  {
    slug: 'forge-athletics-jette',
    name: 'Forge Athletics Jette',
    businessSlug: 'forge-athletics',
    district: 'jette',
    lat: 50.8792,
    lon: 4.3271,
    address: 'Rue Léon Theodor 45',
    postalCode: '1090',
    categories: ['crossfit', 'boxing'],
    amenities: ['Douches', 'Sacs de frappe', 'Vestiaires'],
    description: 'La box du nord-ouest : CrossFit, conditionnement et boxe technique.',
  },
  {
    slug: 'atelier-pulse-woluwe',
    name: 'Atelier Pulse Woluwe',
    businessSlug: 'atelier-pulse',
    district: 'woluwe-saint-pierre',
    lat: 50.8331,
    lon: 4.4372,
    address: 'Avenue de Tervueren 250',
    postalCode: '1150',
    categories: ['ems', 'recovery'],
    amenities: ['Tenue fournie', 'Douches', 'Pressothérapie'],
    description: 'EMS et récupération assistée, sur rendez-vous, séances de 20 à 40 minutes.',
  },
  {
    slug: 'ride-house-ixelles',
    name: 'Ride House',
    businessSlug: 'move-collective',
    district: 'ixelles',
    lat: 50.8218,
    lon: 4.3661,
    address: 'Chaussée d’Ixelles 210',
    postalCode: '1050',
    categories: ['cycling', 'fitness'],
    amenities: ['Chaussures fournies', 'Douches', 'Serviettes'],
    description: 'Cours de cycling en salle immersive, 45 minutes, musique live tous les vendredis.',
  },
  {
    slug: 'dojo-central-saint-josse',
    name: 'Dojo Central',
    businessSlug: 'forge-athletics',
    district: 'saint-josse',
    lat: 50.8541,
    lon: 4.3719,
    address: 'Rue Verte 120',
    postalCode: '1210',
    categories: ['arts-martiaux', 'boxing'],
    amenities: ['Tatamis', 'Vestiaires', 'Prêt de kimono'],
    description: 'Judo, jiu-jitsu brésilien et boxe anglaise. Cours découverte pour adultes débutants.',
  },
  {
    slug: 'aqua-molenbeek',
    name: 'Aqua Molenbeek',
    businessSlug: 'club-cinquantenaire',
    district: 'molenbeek',
    lat: 50.8561,
    lon: 4.3258,
    address: 'Rue Osseghem 90',
    postalCode: '1080',
    categories: ['natation', 'recovery'],
    amenities: ['Piscine 25 m', 'Sauna', 'Vestiaires familiaux'],
    description: 'Piscine de quartier avec cours d’aquafitness et créneaux nage libre.',
  },
  {
    slug: 'studio-lumen-evere',
    name: 'Studio Lumen Evere',
    businessSlug: 'studio-lumen',
    district: 'evere',
    lat: 50.8721,
    lon: 4.4011,
    address: 'Avenue Henri Conscience 150',
    postalCode: '1140',
    categories: ['yoga', 'pilates'],
    amenities: ['Tapis fournis', 'Parking', 'Vestiaires'],
    description: 'Yoga Hatha et Pilates au sol, petits groupes, horaires du matin et du soir.',
  },
  {
    slug: 'run-club-watermael',
    name: 'Run Club Watermael',
    businessSlug: 'nordic-fit',
    district: 'watermael-boitsfort',
    lat: 50.7996,
    lon: 4.4131,
    address: 'Drève du Rembucher 8',
    postalCode: '1170',
    categories: ['running', 'fitness'],
    amenities: ['Vestiaires', 'Consigne', 'Coach'],
    description: 'Sorties encadrées en forêt de Soignes, tous niveaux, du 5 km au fractionné.',
  },
  {
    slug: 'padel-koekelberg',
    name: 'Padel Koekelberg',
    businessSlug: 'racket-house',
    district: 'koekelberg',
    lat: 50.8631,
    lon: 4.3294,
    address: 'Boulevard Léopold II 200',
    postalCode: '1081',
    categories: ['padel', 'fitness'],
    amenities: ['3 terrains', 'Location raquette', 'Bar'],
    description: 'Trois terrains extérieurs couverts, réservation à l’heure et initiations débutants.',
  },
  {
    slug: 'vertical-lab-forest',
    name: 'Vertical Lab Forest',
    businessSlug: 'vertical-lab',
    district: 'forest',
    lat: 50.8089,
    lon: 4.3198,
    address: 'Rue de Mérode 350',
    postalCode: '1190',
    categories: ['escalade'],
    amenities: ['Bloc uniquement', 'Location chaussons', 'Café'],
    description: 'Salle de bloc conviviale, ouverte tard, parfaite pour une première séance.',
  },
];

export interface SeedOffer {
  venueSlug: string;
  categorySlug: string;
  title: string;
  description: string;
  experienceType:
    | 'FREE_TRIAL'
    | 'DISCOVERY_PRICE'
    | 'DISCOVERY_PACK'
    | 'INITIATION'
    | 'DAY_PASS'
    | 'BEGINNER_CLASS'
    | 'PREMIUM_EXPERIENCE';
  /** Minor units. */
  price: number;
  referencePrice: number | null;
  durationMinutes: number;
  capacity: number;
  skillLevel: 'ALL_LEVELS' | 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  /** Local wall-clock start times, expanded across the coming weeks. */
  times: string[];
  daysOfWeek: number[];
  whatToBring: string[];
}

export const OFFERS: SeedOffer[] = [
  {
    venueSlug: 'studio-move-ixelles',
    categorySlug: 'pilates',
    title: 'Pilates Reformer — Première séance',
    description:
      'Découvre le Pilates Reformer en petit groupe (6 personnes maximum). Le coach adapte chaque exercice à ton niveau et t’explique la machine pas à pas. Aucune expérience nécessaire.',
    experienceType: 'DISCOVERY_PRICE',
    price: 1000,
    referencePrice: 2800,
    durationMinutes: 55,
    capacity: 6,
    skillLevel: 'BEGINNER',
    times: ['07:00', '12:30', '18:30'],
    daysOfWeek: [1, 2, 3, 4, 5],
    whatToBring: ['Chaussettes antidérapantes', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'studio-move-ixelles',
    categorySlug: 'yoga',
    title: 'Vinyasa Flow — Cours découverte',
    description:
      'Un enchaînement fluide synchronisé sur la respiration. Cours ouvert à tous, variations proposées pour les débutants comme pour les pratiquants confirmés.',
    experienceType: 'FREE_TRIAL',
    price: 0,
    referencePrice: 2200,
    durationMinutes: 60,
    capacity: 14,
    skillLevel: 'ALL_LEVELS',
    times: ['09:30', '19:00'],
    daysOfWeek: [1, 3, 6],
    whatToBring: ['Tenue confortable'],
  },
  {
    venueSlug: 'atelier-pulse-saint-gilles',
    categorySlug: 'ems',
    title: 'EMS — Première séance gratuite',
    description:
      'Vingt minutes d’électrostimulation encadrées en solo par un coach. L’équivalent d’une séance de renforcement classique, sans charge sur les articulations. Tenue fournie.',
    experienceType: 'FREE_TRIAL',
    price: 0,
    referencePrice: 4500,
    durationMinutes: 25,
    capacity: 2,
    skillLevel: 'ALL_LEVELS',
    times: ['08:00', '10:00', '17:00', '18:00', '19:00'],
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    whatToBring: ['Chaussettes', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'nordic-fit-schaerbeek',
    categorySlug: 'boxing',
    title: 'Boxing — Cours découverte',
    description:
      'Technique de base, travail au sac et conditionnement. Le coach corrige la garde et les déplacements dès la première séance. Gants prêtés sur place.',
    experienceType: 'DISCOVERY_PRICE',
    price: 500,
    referencePrice: 1800,
    durationMinutes: 60,
    capacity: 12,
    skillLevel: 'BEGINNER',
    times: ['12:15', '19:30'],
    daysOfWeek: [1, 2, 4],
    whatToBring: ['Serviette', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'racket-house-woluwe',
    categorySlug: 'padel',
    title: 'Padel — Initiation 60 minutes',
    description:
      'Initiation encadrée par un moniteur : règles, service, volée et placement. Raquettes et balles fournies. Viens seul ou à deux, les groupes sont constitués sur place.',
    experienceType: 'INITIATION',
    price: 1200,
    referencePrice: 2400,
    durationMinutes: 60,
    capacity: 8,
    skillLevel: 'BEGINNER',
    times: ['10:00', '14:00', '20:00'],
    daysOfWeek: [2, 4, 6, 0],
    whatToBring: ['Chaussures de sport propres'],
  },
  {
    venueSlug: 'racket-house-auderghem',
    categorySlug: 'padel',
    title: 'Padel — Première heure découverte',
    description:
      'Une heure de terrain à tarif découverte, raquettes incluses. Parfait pour tester le padel entre amis avant de prendre un abonnement.',
    experienceType: 'DISCOVERY_PRICE',
    price: 900,
    referencePrice: 3200,
    durationMinutes: 60,
    capacity: 4,
    skillLevel: 'ALL_LEVELS',
    times: ['09:00', '13:00', '18:00', '21:00'],
    daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    whatToBring: ['Chaussures de sport propres'],
  },
  {
    venueSlug: 'vertical-lab-anderlecht',
    categorySlug: 'escalade',
    title: 'Escalade de bloc — Initiation',
    description:
      'Deux heures pour apprendre à lire une voie, chuter en sécurité et enchaîner tes premiers blocs. Chaussons inclus dans le tarif découverte.',
    experienceType: 'INITIATION',
    price: 1500,
    referencePrice: 2600,
    durationMinutes: 120,
    capacity: 10,
    skillLevel: 'BEGINNER',
    times: ['10:30', '18:30'],
    daysOfWeek: [3, 6],
    whatToBring: ['Tenue souple', 'Chaussettes'],
  },
  {
    venueSlug: 'forge-athletics-forest',
    categorySlug: 'crossfit',
    title: 'CrossFit — Cours débutant',
    description:
      'Séance dédiée aux débutants : mouvements de base décomposés, charges légères, intensité adaptée. Aucun prérequis, l’objectif est la technique.',
    experienceType: 'BEGINNER_CLASS',
    price: 0,
    referencePrice: 2500,
    durationMinutes: 60,
    capacity: 12,
    skillLevel: 'BEGINNER',
    times: ['07:30', '18:00', '19:15'],
    daysOfWeek: [1, 3, 5],
    whatToBring: ['Serviette', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'ride-house-ixelles',
    categorySlug: 'cycling',
    title: 'Cycling — Première séance',
    description:
      'Quarante-cinq minutes de cycling immersif : lumière, son et un coach qui rythme l’effort. Chaussures et serviette fournies.',
    experienceType: 'DISCOVERY_PRICE',
    price: 800,
    referencePrice: 2000,
    durationMinutes: 45,
    capacity: 20,
    skillLevel: 'ALL_LEVELS',
    times: ['07:00', '12:30', '18:15', '19:30'],
    daysOfWeek: [1, 2, 3, 4, 5],
    whatToBring: ['Bouteille d’eau'],
  },
  {
    venueSlug: 'club-cinquantenaire',
    categorySlug: 'natation',
    title: 'Accès journée piscine & bien-être',
    description:
      'Accès libre à la piscine 25 m, au sauna et au hammam pour une journée complète, plus le plateau cardio si tu veux enchaîner.',
    experienceType: 'DAY_PASS',
    price: 1400,
    referencePrice: 2800,
    durationMinutes: 240,
    capacity: 30,
    skillLevel: 'ALL_LEVELS',
    times: ['08:00', '14:00'],
    daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    whatToBring: ['Maillot', 'Bonnet de bain', 'Serviette'],
  },
  {
    venueSlug: 'studio-lumen-bruxelles',
    categorySlug: 'yoga',
    title: 'Yoga doux — Séance découverte gratuite',
    description:
      'Une heure de yoga lent centré sur la respiration et la mobilité. Idéal en fin de journée ou pour une toute première approche.',
    experienceType: 'FREE_TRIAL',
    price: 0,
    referencePrice: 1900,
    durationMinutes: 60,
    capacity: 16,
    skillLevel: 'ALL_LEVELS',
    times: ['12:00', '18:45'],
    daysOfWeek: [2, 4, 6],
    whatToBring: ['Tenue confortable'],
  },
  {
    venueSlug: 'studio-lumen-bruxelles',
    categorySlug: 'danse',
    title: 'Danse contemporaine — Cours d’essai',
    description:
      'Échauffement, traversées et courte chorégraphie. Cours ouvert aux adultes débutants, aucune expérience de danse requise.',
    experienceType: 'DISCOVERY_PRICE',
    price: 700,
    referencePrice: 2000,
    durationMinutes: 90,
    capacity: 14,
    skillLevel: 'BEGINNER',
    times: ['19:00'],
    daysOfWeek: [2, 4],
    whatToBring: ['Chaussettes', 'Tenue souple'],
  },
  {
    venueSlug: 'dojo-central-saint-josse',
    categorySlug: 'arts-martiaux',
    title: 'Jiu-jitsu brésilien — Cours découverte',
    description:
      'Initiation au JJB : déplacements au sol, positions de base et premier sparring léger. Kimono prêté pour la séance.',
    experienceType: 'BEGINNER_CLASS',
    price: 500,
    referencePrice: 2200,
    durationMinutes: 75,
    capacity: 16,
    skillLevel: 'BEGINNER',
    times: ['19:30'],
    daysOfWeek: [1, 3, 5],
    whatToBring: ['Short', 'T-shirt', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'atelier-pulse-woluwe',
    categorySlug: 'recovery',
    title: 'Pressothérapie & récupération',
    description:
      'Quarante minutes de récupération assistée : pressothérapie des jambes et étirements guidés. Après une course ou une grosse semaine.',
    experienceType: 'DISCOVERY_PRICE',
    price: 1200,
    referencePrice: 3500,
    durationMinutes: 40,
    capacity: 3,
    skillLevel: 'ALL_LEVELS',
    times: ['11:00', '16:00', '19:00'],
    daysOfWeek: [1, 2, 3, 4, 5],
    whatToBring: ['Chaussettes'],
  },
  {
    venueSlug: 'run-club-watermael',
    categorySlug: 'running',
    title: 'Sortie running encadrée — Gratuit',
    description:
      'Sortie de groupe en forêt de Soignes avec allures séparées (5’30, 6’00, 6’30 au km). Consigne disponible et retour en étirements.',
    experienceType: 'FREE_TRIAL',
    price: 0,
    referencePrice: 1200,
    durationMinutes: 60,
    capacity: 25,
    skillLevel: 'ALL_LEVELS',
    times: ['09:00', '18:30'],
    daysOfWeek: [3, 6],
    whatToBring: ['Chaussures de running', 'Veste selon météo'],
  },
  {
    venueSlug: 'nordic-fit-etterbeek',
    categorySlug: 'fitness',
    title: 'Accès découverte + bilan coach',
    description:
      'Accès complet à la salle pendant une journée, précédé d’un bilan de 20 minutes avec un coach pour cadrer tes objectifs.',
    experienceType: 'DAY_PASS',
    price: 500,
    referencePrice: 2200,
    durationMinutes: 120,
    capacity: 20,
    skillLevel: 'ALL_LEVELS',
    times: ['08:00', '12:00', '17:30'],
    daysOfWeek: [1, 2, 3, 4, 5],
    whatToBring: ['Serviette', 'Chaussures propres'],
  },
  {
    venueSlug: 'studio-move-uccle',
    categorySlug: 'pilates',
    title: 'Pilates Reformer Uccle — Essai',
    description:
      'Même méthode qu’à Ixelles, dans un studio plus intimiste avec sauna infrarouge accessible après la séance.',
    experienceType: 'DISCOVERY_PRICE',
    price: 1200,
    referencePrice: 3000,
    durationMinutes: 55,
    capacity: 5,
    skillLevel: 'BEGINNER',
    times: ['09:00', '18:00'],
    daysOfWeek: [1, 2, 4, 5],
    whatToBring: ['Chaussettes antidérapantes'],
  },
  {
    venueSlug: 'forge-athletics-jette',
    categorySlug: 'boxing',
    title: 'Boxe technique — Séance d’essai',
    description:
      'Travail technique au sac et aux pattes d’ours, sans opposition. Le coach corrige individuellement pendant toute la séance.',
    experienceType: 'DISCOVERY_PRICE',
    price: 600,
    referencePrice: 2000,
    durationMinutes: 60,
    capacity: 10,
    skillLevel: 'BEGINNER',
    times: ['18:30', '20:00'],
    daysOfWeek: [2, 4],
    whatToBring: ['Serviette', 'Bandes si tu en as'],
  },
  {
    venueSlug: 'aqua-molenbeek',
    categorySlug: 'natation',
    title: 'Aquafitness — Cours découverte',
    description:
      'Cours collectif en petite profondeur : cardio et renforcement sans impact, encadré par un maître-nageur.',
    experienceType: 'FREE_TRIAL',
    price: 0,
    referencePrice: 1500,
    durationMinutes: 45,
    capacity: 18,
    skillLevel: 'ALL_LEVELS',
    times: ['10:00', '19:00'],
    daysOfWeek: [2, 5],
    whatToBring: ['Maillot', 'Bonnet de bain'],
  },
  {
    venueSlug: 'studio-lumen-evere',
    categorySlug: 'pilates',
    title: 'Pilates au sol — Première séance',
    description:
      'Renforcement profond, gainage et mobilité au tapis. Format accessible, sans machine, avec corrections individuelles.',
    experienceType: 'DISCOVERY_PRICE',
    price: 800,
    referencePrice: 1800,
    durationMinutes: 55,
    capacity: 12,
    skillLevel: 'ALL_LEVELS',
    times: ['09:30', '18:30'],
    daysOfWeek: [1, 3, 5],
    whatToBring: ['Chaussettes', 'Tenue souple'],
  },
  {
    venueSlug: 'padel-koekelberg',
    categorySlug: 'padel',
    title: 'Padel — Initiation débutants',
    description:
      'Une heure d’initiation avec moniteur sur terrain couvert. Matériel fourni, groupes de quatre maximum.',
    experienceType: 'INITIATION',
    price: 1000,
    referencePrice: 2400,
    durationMinutes: 60,
    capacity: 4,
    skillLevel: 'BEGINNER',
    times: ['11:00', '17:00', '19:00'],
    daysOfWeek: [1, 3, 6, 0],
    whatToBring: ['Chaussures de sport propres'],
  },
  {
    venueSlug: 'vertical-lab-forest',
    categorySlug: 'escalade',
    title: 'Bloc — Entrée découverte',
    description:
      'Accès libre à la salle de bloc avec chaussons inclus. Un membre de l’équipe fait le tour des règles de sécurité à l’arrivée.',
    experienceType: 'DISCOVERY_PRICE',
    price: 900,
    referencePrice: 1900,
    durationMinutes: 120,
    capacity: 15,
    skillLevel: 'ALL_LEVELS',
    times: ['12:00', '17:00', '20:00'],
    daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    whatToBring: ['Tenue souple', 'Chaussettes'],
  },
  {
    venueSlug: 'nordic-fit-etterbeek',
    categorySlug: 'crossfit',
    title: 'Cross training — Cours d’essai',
    description:
      'Circuit collectif mêlant haltères, rameur et poids de corps. Intensité modulable, coach présent du début à la fin.',
    experienceType: 'BEGINNER_CLASS',
    price: 700,
    referencePrice: 2400,
    durationMinutes: 60,
    capacity: 14,
    skillLevel: 'ALL_LEVELS',
    times: ['12:15', '19:00'],
    daysOfWeek: [2, 4],
    whatToBring: ['Serviette', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'club-cinquantenaire',
    categorySlug: 'recovery',
    title: 'Sauna & hammam — Accès découverte',
    description:
      'Accès à l’espace bien-être en dehors des heures de pointe : sauna, hammam et bassin de récupération.',
    experienceType: 'PREMIUM_EXPERIENCE',
    price: 1800,
    referencePrice: 3600,
    durationMinutes: 120,
    capacity: 12,
    skillLevel: 'ALL_LEVELS',
    times: ['14:00', '20:00'],
    daysOfWeek: [1, 2, 3, 4, 5],
    whatToBring: ['Maillot', 'Serviette', 'Claquettes'],
  },
  {
    venueSlug: 'studio-move-ixelles',
    categorySlug: 'recovery',
    title: 'Mobilité & étirements — Gratuit',
    description:
      'Séance courte centrée sur les hanches et les épaules, idéale en complément d’une pratique sportive régulière.',
    experienceType: 'FREE_TRIAL',
    price: 0,
    referencePrice: 1600,
    durationMinutes: 45,
    capacity: 10,
    skillLevel: 'ALL_LEVELS',
    times: ['13:00'],
    daysOfWeek: [3],
    whatToBring: ['Tenue confortable'],
  },
  {
    venueSlug: 'atelier-pulse-saint-gilles',
    categorySlug: 'personal-training',
    title: 'Personal training — Séance découverte',
    description:
      'Un coach, un objectif, une heure. Bilan de mobilité puis séance sur mesure. Compte rendu envoyé après la séance.',
    experienceType: 'DISCOVERY_PRICE',
    price: 2000,
    referencePrice: 6500,
    durationMinutes: 60,
    capacity: 1,
    skillLevel: 'ALL_LEVELS',
    times: ['07:00', '09:00', '17:00'],
    daysOfWeek: [1, 2, 3, 4, 5],
    whatToBring: ['Serviette', 'Chaussures propres'],
  },
  {
    venueSlug: 'ride-house-ixelles',
    categorySlug: 'fitness',
    title: 'Renforcement express — 30 minutes',
    description:
      'Format court entre midi et deux : haut du corps, gainage et mobilité. Douches disponibles pour repartir au bureau.',
    experienceType: 'DISCOVERY_PRICE',
    price: 600,
    referencePrice: 1500,
    durationMinutes: 30,
    capacity: 16,
    skillLevel: 'ALL_LEVELS',
    times: ['12:00', '12:45'],
    daysOfWeek: [1, 2, 3, 4, 5],
    whatToBring: ['Serviette'],
  },
  {
    venueSlug: 'dojo-central-saint-josse',
    categorySlug: 'boxing',
    title: 'Boxe anglaise — Initiation',
    description:
      'Garde, jab, direct et déplacements. Séance d’initiation en groupe réduit, gants prêtés.',
    experienceType: 'INITIATION',
    price: 500,
    referencePrice: 1800,
    durationMinutes: 60,
    capacity: 12,
    skillLevel: 'BEGINNER',
    times: ['18:00'],
    daysOfWeek: [2, 4, 6],
    whatToBring: ['Serviette', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'run-club-watermael',
    categorySlug: 'fitness',
    title: 'Renfo du coureur — Séance d’essai',
    description:
      'Renforcement spécifique course à pied : chaînes postérieures, pieds et gainage. Complément idéal aux sorties.',
    experienceType: 'DISCOVERY_PRICE',
    price: 600,
    referencePrice: 1600,
    durationMinutes: 45,
    capacity: 14,
    skillLevel: 'ALL_LEVELS',
    times: ['19:00'],
    daysOfWeek: [2],
    whatToBring: ['Tapis si tu en as', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'forge-athletics-forest',
    categorySlug: 'personal-training',
    title: 'Bilan & coaching individuel',
    description:
      'Séance individuelle avec évaluation de la mobilité et plan d’entraînement sur quatre semaines remis à la fin.',
    experienceType: 'PREMIUM_EXPERIENCE',
    price: 2500,
    referencePrice: 7000,
    durationMinutes: 75,
    capacity: 1,
    skillLevel: 'ALL_LEVELS',
    times: ['10:00', '16:00'],
    daysOfWeek: [1, 3, 5],
    whatToBring: ['Serviette', 'Chaussures propres'],
  },
  {
    venueSlug: 'racket-house-woluwe',
    categorySlug: 'tennis',
    title: 'Tennis — Cours collectif découverte',
    description:
      'Cours collectif d’une heure sur court couvert, quatre joueurs maximum. Raquette prêtée si nécessaire.',
    experienceType: 'DISCOVERY_PRICE',
    price: 1400,
    referencePrice: 3000,
    durationMinutes: 60,
    capacity: 4,
    skillLevel: 'BEGINNER',
    times: ['10:00', '18:00'],
    daysOfWeek: [3, 6],
    whatToBring: ['Chaussures de tennis'],
  },
  {
    venueSlug: 'aqua-molenbeek',
    categorySlug: 'recovery',
    title: 'Sauna après nage — Découverte',
    description: 'Accès sauna et bassin froid, en accès libre après ta longueur du soir.',
    experienceType: 'DISCOVERY_PRICE',
    price: 700,
    referencePrice: 1500,
    durationMinutes: 60,
    capacity: 8,
    skillLevel: 'ALL_LEVELS',
    times: ['20:00'],
    daysOfWeek: [2, 4],
    whatToBring: ['Maillot', 'Serviette'],
  },
  {
    venueSlug: 'studio-lumen-evere',
    categorySlug: 'yoga',
    title: 'Hatha yoga — Cours d’essai gratuit',
    description:
      'Postures tenues, respiration et relaxation finale. Cours calme, adapté aux débutants complets.',
    experienceType: 'FREE_TRIAL',
    price: 0,
    referencePrice: 1800,
    durationMinutes: 75,
    capacity: 12,
    skillLevel: 'BEGINNER',
    times: ['09:00', '19:30'],
    daysOfWeek: [2, 4],
    whatToBring: ['Tenue confortable'],
  },
  {
    venueSlug: 'studio-move-uccle',
    categorySlug: 'recovery',
    title: 'Sauna infrarouge — Session découverte',
    description: 'Trente minutes de sauna infrarouge individuel, à réserver après ta séance.',
    experienceType: 'DISCOVERY_PRICE',
    price: 1000,
    referencePrice: 2500,
    durationMinutes: 30,
    capacity: 2,
    skillLevel: 'ALL_LEVELS',
    times: ['11:00', '15:00', '19:30'],
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    whatToBring: ['Serviette'],
  },
  {
    venueSlug: 'vertical-lab-anderlecht',
    categorySlug: 'fitness',
    title: 'Renforcement grimpeur — Essai',
    description:
      'Travail de préhension, de gainage et d’épaules spécifique à l’escalade. Ouvert dès le niveau débutant.',
    experienceType: 'DISCOVERY_PRICE',
    price: 800,
    referencePrice: 2000,
    durationMinutes: 50,
    capacity: 10,
    skillLevel: 'ALL_LEVELS',
    times: ['18:00'],
    daysOfWeek: [2, 4],
    whatToBring: ['Tenue souple'],
  },
  {
    venueSlug: 'nordic-fit-schaerbeek',
    categorySlug: 'fitness',
    title: 'Circuit training — Première séance',
    description:
      'Circuit de 45 minutes en petits groupes : cardio, force et mobilité. Le coach adapte chaque atelier.',
    experienceType: 'FREE_TRIAL',
    price: 0,
    referencePrice: 1800,
    durationMinutes: 45,
    capacity: 12,
    skillLevel: 'ALL_LEVELS',
    times: ['07:30', '17:45'],
    daysOfWeek: [1, 3, 5],
    whatToBring: ['Serviette', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'padel-koekelberg',
    categorySlug: 'fitness',
    title: 'Préparation physique padel',
    description: 'Travail d’appuis, de rotation et d’explosivité pour progresser plus vite sur le terrain.',
    experienceType: 'DISCOVERY_PRICE',
    price: 700,
    referencePrice: 1800,
    durationMinutes: 45,
    capacity: 10,
    skillLevel: 'ALL_LEVELS',
    times: ['18:00'],
    daysOfWeek: [4],
    whatToBring: ['Chaussures de sport propres'],
  },
  {
    venueSlug: 'club-cinquantenaire',
    categorySlug: 'fitness',
    title: 'Plateau cardio — Accès découverte',
    description: 'Accès au plateau cardio et musculation avec présentation des machines à l’arrivée.',
    experienceType: 'DAY_PASS',
    price: 900,
    referencePrice: 2000,
    durationMinutes: 120,
    capacity: 25,
    skillLevel: 'ALL_LEVELS',
    times: ['07:00', '12:00', '18:00'],
    daysOfWeek: [1, 2, 3, 4, 5],
    whatToBring: ['Serviette', 'Chaussures propres'],
  },
  {
    venueSlug: 'atelier-pulse-woluwe',
    categorySlug: 'ems',
    title: 'EMS Woluwe — Séance découverte',
    description: 'Séance EMS de 20 minutes en solo, encadrée, avec bilan de composition corporelle offert.',
    experienceType: 'DISCOVERY_PRICE',
    price: 1000,
    referencePrice: 4500,
    durationMinutes: 25,
    capacity: 2,
    skillLevel: 'ALL_LEVELS',
    times: ['09:00', '12:00', '18:30'],
    daysOfWeek: [1, 2, 3, 4, 5],
    whatToBring: ['Chaussettes', 'Bouteille d’eau'],
  },
  {
    venueSlug: 'forge-athletics-jette',
    categorySlug: 'crossfit',
    title: 'CrossFit Jette — Cours débutant',
    description: 'Fondamentaux CrossFit sur trois séances par semaine, charges légères et technique d’abord.',
    experienceType: 'BEGINNER_CLASS',
    price: 0,
    referencePrice: 2500,
    durationMinutes: 60,
    capacity: 12,
    skillLevel: 'BEGINNER',
    times: ['07:00', '19:00'],
    daysOfWeek: [2, 4, 6],
    whatToBring: ['Serviette', 'Bouteille d’eau'],
  },
];
